substitutions:
  device_name: probreeze-dehumidifier
  friendly_name: ProBreeze Dehumidifier

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
  
# Improve stability on ESP32-C6
preferences:
  flash_write_interval: 5min

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Web interface for diagnostics
web_server:
  port: 80
  version: 3
  log: true

# UART for Tuya MCU communication
uart:
  rx_pin: GPIO21  # Connect to Tuya MCU TX
  tx_pin: GPIO22  # Connect to Tuya MCU RX
  baud_rate: 9600

# Tuya MCU integration
tuya:

# ===========================
# Switches
# ===========================

switch:
  # Main power control (DP1)
  - platform: tuya
    name: "Power"
    icon: "mdi:power"
    switch_datapoint: 1

  # Ionizer function (DP10)
  - platform: tuya
    name: "Ionizer"
    icon: "mdi:air-filter"
    switch_datapoint: 10

  # Child lock (DP16)
  - platform: tuya
    name: "Child Lock"
    icon: "mdi:lock"
    switch_datapoint: 16

  # Filter reset (DP20) - Reset filter life counter
  - platform: tuya
    name: "Filter Reset"
    icon: "mdi:air-filter"
    switch_datapoint: 20

# ===========================
# Number Controls
# ===========================

number:
  # Target humidity setpoint (DP2)
  - platform: tuya
    name: "Target Humidity"
    icon: "mdi:water-percent"
    number_datapoint: 2
    min_value: 30
    max_value: 80
    step: 5
    unit_of_measurement: "%"

# ===========================
# Sensors
# ===========================

sensor:
  # Current humidity reading (DP6)
  - platform: tuya
    name: "Current Humidity"
    icon: "mdi:water-percent"
    sensor_datapoint: 6
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement

  # Current temperature reading (DP7)
  - platform: tuya
    name: "Temperature"
    icon: "mdi:thermometer"
    sensor_datapoint: 7
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  # Fault bitmap (DP19) - Raw value showing all fault states
  # Bits: 0=Tank Full, 1=Cleaning Required, 2=Error E1, 3=Temp<5°C,
  #       4=Temp>38°C, 5=Humidity<25%, 6=Coil Error, 7=Motor Error
  - platform: tuya
    id: fault_bitmap
    name: "Fault Bitmap (raw)"
    sensor_datapoint: 19
    entity_category: diagnostic

  # Filter life remaining (DP23)
  - platform: tuya
    name: "Filter Life"
    icon: "mdi:air-filter"
    sensor_datapoint: 23
    unit_of_measurement: "%"
    entity_category: diagnostic
    state_class: measurement

  # Client ID (DP102) - Tuya device identifier
  - platform: tuya
    name: "Client ID"
    sensor_datapoint: 102
    entity_category: diagnostic

  # Equipment type (DP104) - Device type identifier
  - platform: tuya
    name: "Equipment Type"
    sensor_datapoint: 104
    entity_category: diagnostic

  # WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal"
    icon: "mdi:wifi"
    update_interval: 60s
    entity_category: diagnostic

  # Device uptime
  - platform: uptime
    name: "Uptime"
    icon: "mdi:clock-outline"
    entity_category: diagnostic

# ===========================
# Binary Sensors (Fault Detection)
# ===========================

binary_sensor:
  # Tank full indicator (Bit 0 of DP19)
  - platform: template
    name: "Tank Full"
    icon: "mdi:cup-water"
    device_class: problem
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 1) != 0;

  # Filter cleaning required (Bit 1 of DP19)
  - platform: template
    name: "Cleaning Required"
    icon: "mdi:broom"
    device_class: problem
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 2) != 0;

  # General error E1 (Bit 2 of DP19)
  - platform: template
    name: "Error E1"
    icon: "mdi:alert-circle"
    device_class: problem
    entity_category: diagnostic
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 4) != 0;

  # Temperature too low warning (Bit 3 of DP19)
  - platform: template
    name: "Temperature Too Low (<5°C)"
    icon: "mdi:thermometer-low"
    device_class: problem
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 8) != 0;

  # Temperature too high warning (Bit 4 of DP19)
  - platform: template
    name: "Temperature Too High (>38°C)"
    icon: "mdi:thermometer-high"
    device_class: problem
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 16) != 0;

  # Humidity too low warning (Bit 5 of DP19)
  - platform: template
    name: "Humidity Too Low (<25%)"
    icon: "mdi:water-alert"
    device_class: problem
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 32) != 0;

  # Coil sensor error (Bit 6 of DP19)
  - platform: template
    name: "Coil Error"
    icon: "mdi:alert"
    device_class: problem
    entity_category: diagnostic
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 64) != 0;

  # Motor error (Bit 7 of DP19)
  - platform: template
    name: "Motor Error"
    icon: "mdi:engine-off"
    device_class: problem
    entity_category: diagnostic
    lambda: |-
      return ((uint32_t) id(fault_bitmap).state & 128) != 0;

# ===========================
# Select Controls
# ===========================

select:
  # Fan speed control (DP4)
  - platform: tuya
    name: "Fan Speed"
    icon: "mdi:fan"
    enum_datapoint: 4
    options:
      0: "Low"
      1: "High"

  # Operating mode (DP5)
  - platform: tuya
    name: "Mode"
    icon: "mdi:vector-combine"
    enum_datapoint: 5
    options:
      0: "Auto (Target)"
      1: "Dry (Continuous)"
      2: "Night"

  # Timer setting (DP17)
  - platform: tuya
    name: "Timer"
    icon: "mdi:timer"
    enum_datapoint: 17
    options:
      0: "Cancel"
      1: "1h"
      2: "2h"
      3: "3h"
      4: "4h"
      5: "5h"
      6: "6h"
      7: "7h"
      8: "8h"
      9: "9h"
      10: "10h"
      11: "11h"
      12: "12h"
      13: "13h"
      14: "14h"
      15: "15h"
      16: "16h"
      17: "17h"
      18: "18h"
      19: "19h"
      20: "20h"
      21: "21h"
      22: "22h"
      23: "23h"
      24: "24h"

  # Temperature unit (DP24)
  - platform: tuya
    name: "Temperature Unit"
    icon: "mdi:temperature-celsius"
    enum_datapoint: 24
    options:
      0: "Celsius"
      1: "Fahrenheit"

# ===========================
# Buttons
# ===========================

button:
  # Restart ESP32 remotely
  - platform: restart
    name: "Restart"
    icon: "mdi:restart"
    entity_category: diagnostic
